---
  - name: Copy model archive to host
    copy:
      src: ~/models.zip
      dest: ~/models.zip


  - name: install unzip
    become: true
    apt:
      name: unzip
      state: latest

  - name: unzip models
    ansible.builtin.unarchive:
      src: ~/models.zip
      dest: ~/
      remote_src: yes

