---
  - name: Install pip3
    become: true
    apt:
     name: python3-pip
     state: latest

  - name: Install docker python package
    pip:
      name: docker

  - name: Load image from archive
    docker_image:
      name: testreuse-craft
      push: no
      load_path: testreuse-craft.tar
      source: load

