---
  

  - name: Install docker python package
    pip:
      name: docker

  - name: Restart service docker
    ansible.builtin.service:
     name: docker
     state: restarted
    become: true

  - name: Load image from archive
    docker_image:
      name: testreuse-craft
      push: no
      load_path: ~/testreuse-craft.tar
      source: load
      state: present

  - name: Create a container
    docker_container:
      name: testreuse-craft
      image: testreuse-craft
      privileged: yes
      network_mode: host
      volumes:
        - /home/usiusi/models:/root/models
      command: sleep infinity
