---
  

  - name: Install docker python package
    pip:
      name: docker

  - name: Restart service docker
    ansible.builtin.service:
     name: docker
     state: restarted
    become: true

  - name: Load image from archive
    command: docker import ~/testreuse-craft.tar testreuse-craft

  - name: Create a container
    docker_container:
      name: testreuse-craft
      image: testreuse-craft
      privileged: yes
      network_mode: host
      volumes:
        - /home/usiusi/models:/root/models
      command: sleep infinity

  - name: Run appium in the container
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -dmS appium; screen -S appium -X stuff 'appium\n'"
      chdir: /root

  - name: create server screen
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -dmS server; screen -S server -X stuff 'bash\n'"
      chdir: /root/test-reuse/matching-server
    tags:
      -debug


  - name: Run matching server
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -S server -X stuff 'source venv/bin/activate\n; python server.py'"
    tags:
      - debug




