---
  - name: Load image from archive
    command: docker import ~/testreuse-craft.tar testreuse-craft

  - name: Create a container
    docker_container:
      name: testreuse-craft
      image: testreuse-craft
      privileged: yes
      network_mode: host
      volumes:
        - /home/usiusi/models:/root/models
      command: sleep infinity


  - name: Copy config sample to host
    copy:
      src: "config_sample{{host_id}}.csv"
      dest: ~/config_sample.csv


  - name: Copy smaple config to docker
    command: docker cp ~/config_sample.csv testreuse-craft:/root/test-reuse/Craftdroid-Modified/manager

  - name: Create appium screen
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -dmS appium; screen -S appium -X stuff 'bash\n'"
    tags:
      - debug


  - name: Run appium in the container
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -S appium -X stuff 'appium\n'"
      chdir: /root
    tags:
      - debug


  - name: Create bert screen
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -dmS bert; screen -S bert -X stuff 'bash\n'"
      chdir: /root/test-reuse/matching-server
    tags:
      - debug


  - name: Run matching server
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -S server -X stuff 'source venv-bert/bin/activate; bert-serving-start -model_dir /root/models/bert/uncased_L-12_H-768_A-12 -num_worker=1 -port 3333 -port_out 3334\n'"
    tags:
      - debug


  - name: Create server screen
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -dmS server; screen -S server -X stuff 'bash\n'"
      chdir: /root/test-reuse/matching-server


  - name: Run matching server
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -S server -X stuff 'source venv/bin/activate; python server.py\n'"


  - name: Create CraftDroid screen
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -dmS craft; screen -S craft -X stuff 'bash\n'"
      chdir: /root/test-reuse/Craftdroid-Modified


  - name: Run CraftDroid
    community.docker.docker_container_exec:
      container: testreuse-craft
      command: bash -c "screen -S craft -X stuff 'source venv/bin/activate; python run_manager.py\n'"
