---

  - name: install pre
    become: true
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - software-properties-common
      - apt-transport-https
      - ca-certificates 
      - curl
      - gnupg 
      - lsb-release

  - name: Add an apt signing key for Docker
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    become: true
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: apt docker install
    become: true
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Add user to docker group
    become: true
    user:
      name: "{{ansible_user}}"
      group: docker

  - name: check docker started
    service:
      name: docker
      state: started
      enabled: yes



