---
  - name: Stop ATM container
    command: docker container stop testreuse-atm


  - name: Start ATM container
    command: docker container start testreuse-atm
    tags:
      - atm_start

  - name: Copy config sample to host
    copy:
      src: "config_sample{{host_id}}.csv"
      dest: ~/config_sample.csv
    tags:
      - config

  - name: Copy smaple config to docker
    command: docker cp ~/config_sample.csv testreuse-atm:/root/test-reuse/atm/atm_runner
    tags:
      - config


  - name: Wipe screens
    community.docker.docker_container_exec:
      container: testreuse-atm
      command: bash -c "screen -wipe"
    tags:
      - screen_wipe

  - name: Create bert screen
    community.docker.docker_container_exec:
      container: testreuse-atm
      command: bash -c "screen -dmS bert; screen -S bert -X stuff 'bash\n'"
      chdir: /root/test-reuse/matching-server


  - name: Run bert
    community.docker.docker_container_exec:
      container: testreuse-atm
      command: bash -c "screen -S bert -X stuff 'source venv-bert/bin/activate; bert-serving-start -model_dir /root/models/bert/uncased_L-12_H-768_A-12 -num_worker=1 -port 3333 -port_out 3334\n'"


  - name: Create server screen
    community.docker.docker_container_exec:
      container: testreuse-atm
      command: bash -c "screen -dmS server; screen -S server -X stuff 'bash\n'"
      chdir: /root/test-reuse/matching-server


  - name: Run matching server
    community.docker.docker_container_exec:
      container: testreuse-atm
      command: bash -c "screen -S server -X stuff 'source venv/bin/activate; python server.py\n'"


  - name: Create atm screen
    community.docker.docker_container_exec:
      container: testreuse-atm
      command: bash -c "screen -dmS atm; screen -S atm -X stuff 'bash\n'"
      chdir: /root/test-reuse/atm/atm_runner
    tags:
      - debug

  - name: Prepare atm screen
    community.docker.docker_container_exec:
      container: testreuse-atm
      command: bash -c "screen -S atm -X stuff 'source venv/bin/activate\n'"

  - name: Replace config
    community.docker.docker_container_exec:
      container: testreuse-atm
      command: bash -c "screen -S atm -X stuff 'cp config_template/config.yml .\n'"
    tags:
      - config
